### ISSUE TITLE
What is the hyper-parameter in the experiments?

### ISSUE THREAD

**Issue by YexiongLin** [arpit2412/InstanceGM#1]
What is the hyper-parameter (lambda_u) in the experiments?

**Comment by arpit2412** [comment]
Lambda_u is 25. Similar to DivideMix

**Comment by YexiongLin** [comment]
> Lambda_u is 25. Similar to DivideMix

Actually, lambda_u in DivideMix is 25 when the dataset is cifar-10 and the noise rate is 0.5, but when the noise rate is 0.2, the lambda_u is 0. For cifar-100, lambda_u is 25 when the noise rate is 0.2 and lambda_u is 150 when the noise rate is 0.5. What is the lambda_u in your experiments for different datasets and noise rates?

**Comment by arpit2412** [comment]
For cifar10/100 we’ve used 25 as lambda_u for most of the noise rates
