### ISSUE TITLE
Enquiry about red-imagenet data

### ISSUE THREAD

**Issue by MrChenFeng** [arpit2412/InstanceGM#2]
Hi, 
thanks for share your code!
I wonder how do you get and structure the red-imagenet dataset. Seems the OriginalPaper(MentorMix) delete the related codes about red-imagenet and in some related repos (for example FaMUS only dataloader provided.). I think many people would be highly appreciated if you can share this!

Thanks a lot!

**Comment by arpit2412** [comment]
Hi, 
Thanks for the inquiry, i have updated the readme please download the dataset and arrange it according to structure mentioned in redMini.txt, then you can use the same dataloader as mention in InstanceGM
